### ISSUE TITLE
Style Pages

### ISSUE THREAD

**Issue by AmritK10** [AmritK10/Iris_Flower_Predictor#1]
Style the pages or improve the UI.

**Comment by ayushman2001** [comment]
i want to work on this

**Comment by AmritK10** [comment]
Go for it!

**Comment by sapsa07** [comment]
I want to work on this .. can I ?

**Comment by AmritK10** [comment]
Hey @sapsa07 , I've already assigned it to @ayushman2001

**Comment by AmritK10** [comment]
@ayushman2001 , it seems you've still not started to work on this issue. @sapsa07 has already made a pull request. I hope you two can work in collaboration. I'm assigning the issue to him aswell.

**Comment by AmritK10** [comment]
Update the README
